// Run with Node + Playwright installed; against an explicitly started simulation server.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'), path=require('path'), assert=require('assert');
(async()=>{
 const url=process.env.FOCUS_URL||'http://127.0.0.1:8765';
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
 const context=await browser.newContext({viewport:{width:800,height:480}});
 const page=await context.newPage(),errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==url){external.push(route.request().url());return route.abort();}return route.continue();});
 const out=path.resolve('reports/stage3');fs.mkdirSync(out,{recursive:true});
 try {
  await page.goto(url);
  await page.locator('#claim:not([disabled])').waitFor();
  assert.equal((await page.request.get(url+'/api/session')).status(),200);
  await page.screenshot({path:path.join(out,'home-800x480.png')});
  await page.locator('[data-prepare="training"]').click();
  await page.locator('#claim').click();
  await page.locator('input[name="duration"]').fill('60');
  await page.waitForTimeout(400);
  assert.equal(await page.locator('input[name="duration"]').inputValue(),'60','form must survive snapshots');
  await page.locator('#prepare-form button').click();
  await page.locator('#prepare [data-action="start"]:not([disabled])').waitFor();
  await page.screenshot({path:path.join(out,'prepare-800x480.png')});
  await page.locator('#prepare [data-action="start"]').click();
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='进行中');
  const sid=await page.evaluate(async()=> (await(await fetch('/api/session')).json()).snapshot.session_id);
  await page.waitForTimeout(500);
  await page.screenshot({path:path.join(out,'training-800x480.png')});
  await page.locator('[data-action="pause"]').click();
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='已暂停');
  await page.locator('[data-action="resume"]').click();
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='进行中');
  const viewer=await context.newPage();await viewer.goto(url+'/#live');
  await viewer.locator('#claim:not([disabled])').waitFor();await viewer.locator('#claim').click();
  await viewer.waitForFunction(()=>document.querySelector('#notice').textContent.includes('已有操作端'));
  assert.equal(await viewer.locator('[data-action="pause"]').isDisabled(),true);
  await viewer.close();
  // Close the actual websocket: should pause, never restart on reconnect.
  await page.evaluate(()=>socket.close());
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='已暂停');
  await page.locator('#claim:not([disabled])').waitFor();await page.locator('#claim').click();
  assert.equal(await page.locator('#state-label').textContent(),'已暂停');
  await page.reload();
  await page.locator('#claim:not([disabled])').waitFor();
  assert.equal(await page.evaluate(async()=> (await(await fetch('/api/session')).json()).snapshot.session_id),sid);
  await page.locator('#claim').click();await page.locator('[data-action="resume"]').click();
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='进行中');
  await page.locator('[data-action="end"]').click();
  await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>document.querySelector('#report-status').textContent.includes('已完整保存'));
  await page.screenshot({path:path.join(out,'report-800x480.png')});
  await page.locator('#export').click();
  await page.locator('#downloads a').first().waitFor();
  await page.locator('nav a[href="#history"]').click();
  await page.locator('#history-list .record').first().waitFor();
  await page.locator('[name=condition]').selectOption({index:1});await page.locator('#history-form button').click();
  await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'history-800x480.png')});
  await page.locator('nav a[href="#maintenance"]').click();
  await page.locator('#maintenance-status .card').waitFor();
  await page.screenshot({path:path.join(out,'maintenance-800x480.png')});
  await page.locator('nav a[href="#home"]').click();
  await page.locator('[data-prepare="racing"]').click();
  await page.locator('input[name="distance"]').fill('5');
  await page.locator('#prepare-form button').click();
  await page.locator('#prepare [data-action="start"]:not([disabled])').waitFor();
  await page.locator('#prepare [data-action="start"]').click();
  await page.waitForFunction(()=>document.querySelector('#state-label').textContent==='进行中');
  await page.screenshot({path:path.join(out,'racing-800x480.png')});
  await page.waitForFunction(()=>document.querySelector('#report-status').textContent.includes('抵达虚拟终点'));
  const stats=await page.evaluate(()=>({chartInstances:focusDiagnostics.charts.size,latency:focusDiagnostics.latency,version:echarts.version,overflow:document.documentElement.scrollWidth>innerWidth}));
  assert(!stats.overflow,'800px viewport overflow');
  assert.equal(stats.version,'5.6.0');
  assert.equal(external.length,0,'offline resources');
  assert.deepEqual(errors,[]);
  const result={ok:true,session_id:sid,external_requests:external,errors,stats};
  fs.writeFileSync(path.join(out,'browser-result.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify({...result,stats:{...stats,latency_samples:stats.latency.length,latency:undefined}},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});

